package com.inin.analytics.elasticsearch;

public enum ConfigParams {
	SNAPSHOT_WORKING_LOCATION_CONFIG_KEY,
	SNAPSHOT_REPO_NAME_CONFIG_KEY,
	SNAPSHOT_FINAL_DESTINATION,
	ES_WORKING_DIR,
	NUM_SHARDS_PER_INDEX,
	NUM_SHARDS_PER_ORGANIZATION
}
